# Generated by Django 4.0.4 on 2022-05-19 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('idFamilia', models.AutoField(primary_key=True, serialize=False, verbose_name='idFamilia')),
                ('nombreFamilia', models.CharField(max_length=100, verbose_name='nombreFamilia')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='idProducto')),
                ('nombreProducto', models.CharField(max_length=100, verbose_name='nombreProducto')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
            ],
        ),
        migrations.CreateModel(
            name='SubFamilia',
            fields=[
                ('idSubFamilia', models.AutoField(primary_key=True, serialize=False, verbose_name='idSubFamilia')),
                ('SubFamilia', models.CharField(max_length=100, verbose_name='SubFamilia')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
    ]
