# Generated by Django 4.0.4 on 2022-06-29 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='idUsuario')),
                ('username', models.CharField(max_length=100, unique='True', verbose_name='Nombre Usuario')),
                ('email', models.EmailField(max_length=254, unique='True', verbose_name='Correo Electronico')),
                ('nombres', models.CharField(max_length=200, null='False', verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=200, null='False', verbose_name='Apellido')),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('usuario_superuser', models.BooleanField(default=False)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False, verbose_name='idCompra')),
                ('fechaCompra', models.DateField(verbose_name='Fechadecompra')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False, verbose_name='idComuna')),
                ('nombre_comuna', models.CharField(max_length=30, verbose_name='NombreComuna')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False, verbose_name='idEstado')),
                ('estado', models.CharField(max_length=100, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('idEstrategia', models.AutoField(primary_key=True, serialize=False, verbose_name='idEstrategia')),
                ('nombreEstrategia', models.CharField(max_length=30, verbose_name='nombreEstrategia')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('idFamilia', models.AutoField(primary_key=True, serialize=False, verbose_name='idFamilia')),
                ('nombreFamilia', models.CharField(max_length=100, verbose_name='nombreFamilia')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='idProducto')),
                ('nombreProducto', models.CharField(max_length=100, verbose_name='nombreProducto')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='modelo')),
                ('descripcion', models.CharField(max_length=150, verbose_name='descripcion')),
                ('imagen', models.TextField(verbose_name='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False, verbose_name='idRegion')),
                ('nombre_region', models.CharField(max_length=30, verbose_name='nombreregion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='idTipoUsuario')),
                ('tipoUsuario', models.CharField(max_length=100, verbose_name='tipoUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tipopago',
            fields=[
                ('idTipopago', models.AutoField(primary_key=True, serialize=False, verbose_name='idTipopago')),
                ('tipopago', models.CharField(max_length=100, verbose_name='tipopago')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idSucursal', models.AutoField(primary_key=True, serialize=False, verbose_name='idSucursal')),
                ('sucursal', models.CharField(max_length=70, verbose_name='sucursal')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo')),
                ('telefono', models.CharField(max_length=30, verbose_name='telefono')),
                ('idComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='SubFamilia',
            fields=[
                ('idSubFamilia', models.AutoField(primary_key=True, serialize=False, verbose_name='idSubFamilia')),
                ('SubFamilia', models.CharField(max_length=100, verbose_name='subFamilia')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idProvincia', models.AutoField(primary_key=True, serialize=False, verbose_name='idProvincia')),
                ('nombre_provincia', models.CharField(max_length=30, verbose_name='Nombreprovincia')),
                ('region_idRegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='Estrategia_Detalle',
            fields=[
                ('idEstrategiaDetalle', models.AutoField(primary_key=True, serialize=False, verbose_name='idEstrategiaDetalle')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='descripcion')),
                ('idEstrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('idSucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='Provincia_idProvincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincia'),
        ),
        migrations.CreateModel(
            name='Compra_Detalle',
            fields=[
                ('idCompraDetalle', models.AutoField(primary_key=True, serialize=False, verbose_name='idCompraDetalle')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('idcompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compra')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='idEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idSucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idTipopago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipopago'),
        ),
        migrations.AddField(
            model_name='compra',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idTipousuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tipo_usuario'),
        ),
    ]
