# Generated by Django 4.0.4 on 2022-05-26 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_usuario',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estrategia',
            name='nombreEstrategia',
            field=models.CharField(default='2', max_length=30, verbose_name='nombreEstrategia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo_usuario',
            name='tipoUsuario',
            field=models.CharField(default='2', max_length=100, verbose_name='tipoUsuario'),
            preserve_default=False,
        ),
    ]
