# Generated by Django 4.0.4 on 2022-05-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default='5', max_length=50, verbose_name='modelo'),
            preserve_default=False,
        ),
    ]
