# Generated by Django 4.0.4 on 2022-06-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_estrategia_detalle_idestrategia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrategia_detalle',
            name='idEstrategia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estrategia'),
        ),
    ]
