# Generated by Django 3.2.4 on 2022-05-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tipo_usuario_descripcion_compra_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='estado',
        ),
    ]
