# Generated by Django 4.0.4 on 2022-06-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=150, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.TextField(verbose_name='imagen'),
        ),
    ]
