# Generated by Django 4.0.4 on 2022-06-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_estrategia_detalle_idestrategia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra_detalle',
            name='idCompraDetalle',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='idCompraDetalle'),
        ),
    ]
