# Generated by Django 4.0.4 on 2022-06-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='group',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idTipousuario',
        ),
    ]
