# Generated by Django 4.0.4 on 2022-06-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_compra_detalle_idcompradetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='idCompra',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='idCompra'),
        ),
        migrations.AlterField(
            model_name='compra_detalle',
            name='idCompraDetalle',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='idCompraDetalle'),
        ),
    ]
