# Generated by Django 4.0.4 on 2022-06-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_compra_idcompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='idOrden',
            field=models.IntegerField(default=1, verbose_name='orden'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='idCompra',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='idCompra'),
        ),
    ]
