# Generated by Django 4.0.4 on 2022-06-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuario_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_administrador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_superuser',
        ),
    ]
