# Generated by Django 4.0.4 on 2022-06-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usuario_usuario_administrador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='group',
        ),
    ]
